- name: Update all packages
  apt:
    upgrade: dist
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Install essential packages
  package:
    name:
      - fail2ban
      - auditd
      - selinux-basics  # Для Debian
    state: present
